import 'package:freezed_annotation/freezed_annotation.dart';

part 'chat_message.freezed.dart';

/// Who said it.
enum ChatRole {
  /// Plexa. Rendered in the left lane under a "PLEXA" eyebrow.
  bot,

  /// The user. Rendered in the right lane — and, on a reply step, the chip the
  /// user taps IS this message before it is sent.
  user,
}

/// One line in the onboarding thread.
///
/// The web's `ChatBubble` from `components/chat/PlexaChatKit.tsx`. Ids are
/// generated by the controller and are what keys the list — two consecutive
/// identical lines are a real possibility (a retried finalise says the same
/// thing twice) and keying by text would collapse them.
@freezed
abstract class ChatMessage with _$ChatMessage {
  const factory ChatMessage({
    required String id,
    required ChatRole role,
    required String text,

    /// An optional caption under the bubble — `Role set`, `Saved`, `Switched`.
    /// Green, because it is a confirmation that something landed.
    String? badge,
  }) = _ChatMessage;
}
